# smtp server info
ServerHost = "smtp.partner.outlook.cn"
ServerPort = 587

# proxy port for local
ProxyPort = ":8080"
ProxySleep = 5

# log info
LogFile = "logs/mail.log"
Debug = true

# content length. 1M by default
ContLen = 1048576

# the account info use to send mail
[[Senders]]
name = "alarm"
account = "alarm1@your.cn"
password = "pwd1"

[[Senders]]
name = "alarm"
account = "alarm2@your.cn"
password = "pwd2"

[[Senders]]
name = "alarm"
account = "alarm3@your.cn"
password = "pwd3"

[[Senders]]
name = "monitor"
account = "monitor@your.cn"
password = "pwdmonitor"

[[Senders]]
name = "test"
account = "test@your.cn"
password = "pwdtest"

